name: snakemake_default
channels:
  - bioconda
  - conda-forge
  - r
  - defaults
dependencies:
  - python=3.7
  - snakemake
  - bcftools
  - openssl
  - tabix
  - vcftools
  - pygraphviz # graph environmenty
  # R packages:
  - r-base
  - r-tidyverse
  - r-optparse
  - r-ggpubr
  - r-ggrepel
  - r-lemon
  - r-gmp
  - r-rcolorbrewer
  - r-foreach
  - r-doparallel
