name: snakemake_default
channels:
  - bioconda
  - conda-forge
  - r
  - defaults
dependencies:
  - python=3.7
  - snakemake
  - bcftools
  - openssl
  - tabix
  - vcftools
  - pygraphviz # graph environmenty
  # R packages:
  - r-base
  - r-tidyverse
  - r-optparse
